export enum ClientRoutes {
  HOME = '/',
  GAME_ROOM = '/game-room',
  LEADER_BOARD = '/leader-board',
  PROFILE = '/profile',
  TERMS = '/terms',
  SIGN = '/sign',
  SIGNIN = 'signin',
  SIGNUP = 'signup',
  RESET_PASSWORD_EMAIL = 'reset-password-email',
  CONTACT_US = '/contact-us',
  PASSWORD_RESET = '/password-reset/:token',
  CONFIRM_EMAIL = '/confirm-email',
  EMAIL_INFO = '/email-info',
}
