export enum ClientRoutes {
  HOME = '/',
  GAME_ROOM = '/game-room',
  BOT_GAME = '/bot-game',
  USERS_GAME = '/game',
  LEADER_BOARD = '/leader-board',
  PROFILE = '/profile',
  TERMS = '/terms',
  SIGN = '/sign',
  SIGNIN = '/signin',
  SIGNUP = '/signup',
  RESET_PASSWORD_EMAIL = '/reset-password-email',
  CONTACT_US = '/contact-us',
  PASSWORD_RESET = '/password-reset/:token',
  CONFIRM_EMAIL = '/confirm-email',
  EMAIL_INFO = '/email-info',
}

export enum PageTitles {
  BOT_GAME = 'Game vs Bot',
  USERS_GAME = 'Game',
  PROFILE = 'Profile',
  CONFIRM_EMAIL = 'Confirm Email',
  EMAIL_INSTRUCTION = 'Email Instruction',
  RESET_PASSWORD = 'Reset Password',
  TERMS = 'Terms',
  SIGN_IN = 'Sign In',
  SIGN_UP = 'Sign Up',
  EMAIL = 'Email',
}
